// <auto-generated />
using System;
using AquaHub.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AquaHub.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260128125725_AddRemindersAndNotifications")]
    partial class AddRemindersAndNotifications
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AquaHub.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("AquaHub.Models.DosingRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Additive")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("AmountMl")
                        .HasColumnType("double precision");

                    b.Property<int>("TankId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TankId");

                    b.ToTable("DosingRecords");
                });

            modelBuilder.Entity("AquaHub.Models.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<DateTime>("InstalledOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TankId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TankId");

                    b.ToTable("Equipment");

                    b.HasDiscriminator().HasValue("Equipment");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("AquaHub.Models.Livestock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TankId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TankId");

                    b.ToTable("Livestock");

                    b.HasDiscriminator().HasValue("Livestock");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("AquaHub.Models.MaintenanceLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TankId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<double?>("WaterChangePercent")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("TankId");

                    b.ToTable("MaintenanceLogs");
                });

            modelBuilder.Entity("AquaHub.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EmailSent")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ReminderId")
                        .HasColumnType("integer");

                    b.Property<int?>("TankId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("WaterTestId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReminderId");

                    b.HasIndex("TankId");

                    b.HasIndex("UserId");

                    b.HasIndex("WaterTestId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("AquaHub.Models.PhotoLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TankId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TankId");

                    b.ToTable("PhotoLogs");
                });

            modelBuilder.Entity("AquaHub.Models.Reminder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Frequency")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastCompletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NextDueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NotificationHoursBefore")
                        .HasColumnType("integer");

                    b.Property<bool>("SendEmailNotification")
                        .HasColumnType("boolean");

                    b.Property<int?>("TankId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TankId");

                    b.HasIndex("UserId");

                    b.ToTable("Reminders");
                });

            modelBuilder.Entity("AquaHub.Models.Tank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ImagePath")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("VolumeGallons")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Tanks");
                });

            modelBuilder.Entity("AquaHub.Models.UserNotificationSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EmailDigestFrequencyHours")
                        .HasColumnType("integer");

                    b.Property<bool>("EmailNotificationsEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("EquipmentAlertsEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("ReminderNotificationsEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("WaterParameterAlertsEnabled")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserNotificationSettings");
                });

            modelBuilder.Entity("AquaHub.Models.WaterTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("Alkalinity")
                        .HasColumnType("double precision");

                    b.Property<double?>("Ammonia")
                        .HasColumnType("double precision");

                    b.Property<double?>("Calcium")
                        .HasColumnType("double precision");

                    b.Property<double?>("GH")
                        .HasColumnType("double precision");

                    b.Property<double?>("KH")
                        .HasColumnType("double precision");

                    b.Property<double?>("Magnesium")
                        .HasColumnType("double precision");

                    b.Property<double?>("Nitrate")
                        .HasColumnType("double precision");

                    b.Property<double?>("Nitrite")
                        .HasColumnType("double precision");

                    b.Property<double?>("PH")
                        .HasColumnType("double precision");

                    b.Property<double?>("Phosphate")
                        .HasColumnType("double precision");

                    b.Property<double?>("Salinity")
                        .HasColumnType("double precision");

                    b.Property<double?>("TDS")
                        .HasColumnType("double precision");

                    b.Property<int>("TankId")
                        .HasColumnType("integer");

                    b.Property<double?>("Temperature")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TankId");

                    b.ToTable("WaterTests");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserPasskey<string>", b =>
                {
                    b.Property<byte[]>("CredentialId")
                        .HasMaxLength(1024)
                        .HasColumnType("bytea");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CredentialId");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserPasskeys", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AquaHub.Models.Filter", b =>
                {
                    b.HasBaseType("AquaHub.Models.Equipment");

                    b.Property<double>("FlowRate")
                        .HasColumnType("double precision");

                    b.Property<string>("Media")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Filter");
                });

            modelBuilder.Entity("AquaHub.Models.Heater", b =>
                {
                    b.HasBaseType("AquaHub.Models.Equipment");

                    b.Property<decimal>("MaxTemperature")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MinTemperature")
                        .HasColumnType("numeric");

                    b.HasDiscriminator().HasValue("Heater");
                });

            modelBuilder.Entity("AquaHub.Models.Light", b =>
                {
                    b.HasBaseType("AquaHub.Models.Equipment");

                    b.Property<int>("IntensityPercent")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDimmable")
                        .HasColumnType("boolean");

                    b.Property<string>("Schedule")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Spectrum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Wattage")
                        .HasColumnType("double precision");

                    b.HasDiscriminator().HasValue("Light");
                });

            modelBuilder.Entity("AquaHub.Models.ProteinSkimmer", b =>
                {
                    b.HasBaseType("AquaHub.Models.Equipment");

                    b.Property<int>("AirIntake")
                        .HasColumnType("integer");

                    b.Property<double>("Capacity")
                        .HasColumnType("double precision");

                    b.Property<int>("CupFillLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("Equipment", t =>
                        {
                            t.Property("Type")
                                .HasColumnName("ProteinSkimmer_Type");
                        });

                    b.HasDiscriminator().HasValue("ProteinSkimmer");
                });

            modelBuilder.Entity("AquaHub.Models.Coral", b =>
                {
                    b.HasBaseType("AquaHub.Models.Livestock");

                    b.Property<string>("AggressionMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AlkalinityRange")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CalciumRange")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("CanBeFragged")
                        .HasColumnType("boolean");

                    b.Property<string>("CareLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("ColonySize")
                        .HasColumnType("double precision");

                    b.Property<string>("Coloration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CommonDiseases")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CoralFamily")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CoralType")
                        .HasColumnType("integer");

                    b.Property<string>("DosingRequirements")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FeedingFrequency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FlowNeeds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FlowType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FoodTypes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FraggingDifficulty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FraggingMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FraggingNotes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GrowthRate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HasZooxanthellae")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAggressive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsToxic")
                        .HasColumnType("boolean");

                    b.Property<string>("LightIntensityPAR")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LightSpectrum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LightingNeeds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MagnesiumRange")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("OptimalSalinityMax")
                        .HasColumnType("double precision");

                    b.Property<double>("OptimalSalinityMin")
                        .HasColumnType("double precision");

                    b.Property<double>("OptimalTemperatureMax")
                        .HasColumnType("double precision");

                    b.Property<double>("OptimalTemperatureMin")
                        .HasColumnType("double precision");

                    b.Property<string>("Placement")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PolyExtension")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RequiresAcclimation")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiresDosing")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiresFeeding")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiresStableParameters")
                        .HasColumnType("boolean");

                    b.Property<string>("ScientificName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("SpacingRequirement")
                        .HasColumnType("double precision");

                    b.Property<string>("SpecialRequirements")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StressSigns")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("pHRange")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("Livestock", t =>
                        {
                            t.Property("CareLevel")
                                .HasColumnName("Coral_CareLevel");

                            t.Property("Coloration")
                                .HasColumnName("Coral_Coloration");

                            t.Property("CommonDiseases")
                                .HasColumnName("Coral_CommonDiseases");

                            t.Property("FeedingFrequency")
                                .HasColumnName("Coral_FeedingFrequency");

                            t.Property("FoodTypes")
                                .HasColumnName("Coral_FoodTypes");

                            t.Property("OptimalTemperatureMax")
                                .HasColumnName("Coral_OptimalTemperatureMax");

                            t.Property("OptimalTemperatureMin")
                                .HasColumnName("Coral_OptimalTemperatureMin");

                            t.Property("Placement")
                                .HasColumnName("Coral_Placement");

                            t.Property("RequiresAcclimation")
                                .HasColumnName("Coral_RequiresAcclimation");

                            t.Property("SpecialRequirements")
                                .HasColumnName("Coral_SpecialRequirements");

                            t.Property("pHRange")
                                .HasColumnName("Coral_pHRange");
                        });

                    b.HasDiscriminator().HasValue("Coral");
                });

            modelBuilder.Entity("AquaHub.Models.FreshwaterFish", b =>
                {
                    b.HasBaseType("AquaHub.Models.Livestock");

                    b.Property<string>("ActivityLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("AdultSize")
                        .HasColumnType("double precision");

                    b.Property<bool>("AggressiveToOtherFish")
                        .HasColumnType("boolean");

                    b.Property<bool>("AggressiveToSameSpecies")
                        .HasColumnType("boolean");

                    b.Property<int>("AverageLifespanYears")
                        .HasColumnType("integer");

                    b.Property<string>("BodyShape")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BreedingDifficulty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BreedingNotes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BreedingType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CareLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Coloration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CommonDiseases")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Diet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EatsShrimp")
                        .HasColumnType("boolean");

                    b.Property<bool>("EatsSmallFish")
                        .HasColumnType("boolean");

                    b.Property<bool>("EatsSnails")
                        .HasColumnType("boolean");

                    b.Property<string>("FeedingFrequency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FishType")
                        .HasColumnType("integer");

                    b.Property<string>("FoodTypes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HardnessRange")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HasLongFins")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBottomFeeder")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsJumper")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLabyrinthFish")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNocturnal")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSchooling")
                        .HasColumnType("boolean");

                    b.Property<double>("MinTankSize")
                        .HasColumnType("double precision");

                    b.Property<bool>("NipsAtFins")
                        .HasColumnType("boolean");

                    b.Property<double>("OptimalTemperatureMax")
                        .HasColumnType("double precision");

                    b.Property<double>("OptimalTemperatureMin")
                        .HasColumnType("double precision");

                    b.Property<string>("PreferredWaterFlow")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ProneToDropsy")
                        .HasColumnType("boolean");

                    b.Property<bool>("ProneToIch")
                        .HasColumnType("boolean");

                    b.Property<int>("RecommendedSchoolSize")
                        .HasColumnType("integer");

                    b.Property<bool>("RequiresAirstone")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiresCycledTank")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiresDriftwood")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiresHidingSpots")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiresPlants")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiresQuarantine")
                        .HasColumnType("boolean");

                    b.Property<string>("SpecialRequirements")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SwimmingRegion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TankMateCompatibility")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Temperament")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("pHRange")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("Livestock", t =>
                        {
                            t.Property("AdultSize")
                                .HasColumnName("FreshwaterFish_AdultSize");

                            t.Property("AverageLifespanYears")
                                .HasColumnName("FreshwaterFish_AverageLifespanYears");

                            t.Property("BreedingDifficulty")
                                .HasColumnName("FreshwaterFish_BreedingDifficulty");

                            t.Property("BreedingNotes")
                                .HasColumnName("FreshwaterFish_BreedingNotes");

                            t.Property("CareLevel")
                                .HasColumnName("FreshwaterFish_CareLevel");

                            t.Property("Coloration")
                                .HasColumnName("FreshwaterFish_Coloration");

                            t.Property("CommonDiseases")
                                .HasColumnName("FreshwaterFish_CommonDiseases");

                            t.Property("Diet")
                                .HasColumnName("FreshwaterFish_Diet");

                            t.Property("FeedingFrequency")
                                .HasColumnName("FreshwaterFish_FeedingFrequency");

                            t.Property("HardnessRange")
                                .HasColumnName("FreshwaterFish_HardnessRange");

                            t.Property("MinTankSize")
                                .HasColumnName("FreshwaterFish_MinTankSize");

                            t.Property("OptimalTemperatureMax")
                                .HasColumnName("FreshwaterFish_OptimalTemperatureMax");

                            t.Property("OptimalTemperatureMin")
                                .HasColumnName("FreshwaterFish_OptimalTemperatureMin");

                            t.Property("SpecialRequirements")
                                .HasColumnName("FreshwaterFish_SpecialRequirements");

                            t.Property("TankMateCompatibility")
                                .HasColumnName("FreshwaterFish_TankMateCompatibility");

                            t.Property("pHRange")
                                .HasColumnName("FreshwaterFish_pHRange");
                        });

                    b.HasDiscriminator().HasValue("FreshwaterFish");
                });

            modelBuilder.Entity("AquaHub.Models.FreshwaterInvertebrate", b =>
                {
                    b.HasBaseType("AquaHub.Models.Livestock");

                    b.Property<double>("AdultSize")
                        .HasColumnType("double precision");

                    b.Property<bool>("AggressiveTowardsOwnSpecies")
                        .HasColumnType("boolean");

                    b.Property<int>("AverageLifespanYears")
                        .HasColumnType("integer");

                    b.Property<string>("Behavior")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BreedingDifficulty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BreedingNotes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CareLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Coloration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CommonDiseases")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Diet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FeedingFrequency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Habitat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HardnessRange")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("InvertebrateType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAlgaeEater")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPlantSafe")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsScavenger")
                        .HasColumnType("boolean");

                    b.Property<double>("MinTankSize")
                        .HasColumnType("double precision");

                    b.Property<double>("OptimalTemperatureMax")
                        .HasColumnType("double precision");

                    b.Property<double>("OptimalTemperatureMin")
                        .HasColumnType("double precision");

                    b.Property<string>("Placement")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RequiresAcclimation")
                        .HasColumnType("boolean");

                    b.Property<bool>("SensitiveToCopper")
                        .HasColumnType("boolean");

                    b.Property<string>("SpecialRequirements")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TankMateCompatibility")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WaterParameters")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("pHRange")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("FreshwaterInvertebrate");
                });

            modelBuilder.Entity("AquaHub.Models.Plant", b =>
                {
                    b.HasBaseType("AquaHub.Models.Livestock");

                    b.Property<string>("Benefits")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("CanBePropagated")
                        .HasColumnType("boolean");

                    b.Property<string>("CareLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Co2Needs")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Coloration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CommonIssues")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GrowthRate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HardnessRange")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LightingNeeds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LightingRequirement")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("MaxHeight")
                        .HasColumnType("double precision");

                    b.Property<bool>("NitrateAbsorber")
                        .HasColumnType("boolean");

                    b.Property<double>("OptimalTemperatureMax")
                        .HasColumnType("double precision");

                    b.Property<double>("OptimalTemperatureMin")
                        .HasColumnType("double precision");

                    b.Property<bool>("OxygenProducer")
                        .HasColumnType("boolean");

                    b.Property<string>("Placement")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PlantType")
                        .HasColumnType("integer");

                    b.Property<string>("PropagationMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RequiresCO2")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiresFertilization")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiresRootTabs")
                        .HasColumnType("boolean");

                    b.Property<bool>("SafeForShrimp")
                        .HasColumnType("boolean");

                    b.Property<bool>("SafeForSnails")
                        .HasColumnType("boolean");

                    b.Property<string>("SpecialRequirements")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubstrateRequirement")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("pHRange")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("Livestock", t =>
                        {
                            t.Property("CareLevel")
                                .HasColumnName("Plant_CareLevel");

                            t.Property("Coloration")
                                .HasColumnName("Plant_Coloration");

                            t.Property("GrowthRate")
                                .HasColumnName("Plant_GrowthRate");

                            t.Property("HardnessRange")
                                .HasColumnName("Plant_HardnessRange");

                            t.Property("LightingNeeds")
                                .HasColumnName("Plant_LightingNeeds");

                            t.Property("OptimalTemperatureMax")
                                .HasColumnName("Plant_OptimalTemperatureMax");

                            t.Property("OptimalTemperatureMin")
                                .HasColumnName("Plant_OptimalTemperatureMin");

                            t.Property("Placement")
                                .HasColumnName("Plant_Placement");

                            t.Property("SpecialRequirements")
                                .HasColumnName("Plant_SpecialRequirements");

                            t.Property("pHRange")
                                .HasColumnName("Plant_pHRange");
                        });

                    b.HasDiscriminator().HasValue("Plant");
                });

            modelBuilder.Entity("AquaHub.Models.SaltwaterFish", b =>
                {
                    b.HasBaseType("AquaHub.Models.Livestock");

                    b.Property<string>("ActivityLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("AdultSize")
                        .HasColumnType("double precision");

                    b.Property<bool>("AggressiveToOtherFish")
                        .HasColumnType("boolean");

                    b.Property<bool>("AggressiveToSameSpecies")
                        .HasColumnType("boolean");

                    b.Property<int>("AverageLifespanYears")
                        .HasColumnType("integer");

                    b.Property<string>("BodyShape")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BreedingDifficulty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BreedingNotes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CareLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Coloration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CommonDiseases")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Diet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FeedingBehavior")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FeedingFrequency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FishType")
                        .HasColumnType("integer");

                    b.Property<string>("FoodTypes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsJumper")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsReefSafe")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSchooling")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVenomous")
                        .HasColumnType("boolean");

                    b.Property<double>("MinTankSize")
                        .HasColumnType("double precision");

                    b.Property<bool>("NipsAtCorals")
                        .HasColumnType("boolean");

                    b.Property<bool>("NipsAtInvertebrates")
                        .HasColumnType("boolean");

                    b.Property<double>("OptimalSalinityMax")
                        .HasColumnType("double precision");

                    b.Property<double>("OptimalSalinityMin")
                        .HasColumnType("double precision");

                    b.Property<double>("OptimalTemperatureMax")
                        .HasColumnType("double precision");

                    b.Property<double>("OptimalTemperatureMin")
                        .HasColumnType("double precision");

                    b.Property<bool>("ProneToIch")
                        .HasColumnType("boolean");

                    b.Property<int>("RecommendedSchoolSize")
                        .HasColumnType("integer");

                    b.Property<bool>("RequiresHidingSpots")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiresLiveRock")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiresQuarantine")
                        .HasColumnType("boolean");

                    b.Property<string>("SpecialRequirements")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SwimmingRegion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TankMateCompatibility")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Temperament")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("pHRange")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("Livestock", t =>
                        {
                            t.Property("ActivityLevel")
                                .HasColumnName("SaltwaterFish_ActivityLevel");

                            t.Property("AdultSize")
                                .HasColumnName("SaltwaterFish_AdultSize");

                            t.Property("AggressiveToOtherFish")
                                .HasColumnName("SaltwaterFish_AggressiveToOtherFish");

                            t.Property("AggressiveToSameSpecies")
                                .HasColumnName("SaltwaterFish_AggressiveToSameSpecies");

                            t.Property("AverageLifespanYears")
                                .HasColumnName("SaltwaterFish_AverageLifespanYears");

                            t.Property("BodyShape")
                                .HasColumnName("SaltwaterFish_BodyShape");

                            t.Property("BreedingDifficulty")
                                .HasColumnName("SaltwaterFish_BreedingDifficulty");

                            t.Property("BreedingNotes")
                                .HasColumnName("SaltwaterFish_BreedingNotes");

                            t.Property("CareLevel")
                                .HasColumnName("SaltwaterFish_CareLevel");

                            t.Property("Coloration")
                                .HasColumnName("SaltwaterFish_Coloration");

                            t.Property("CommonDiseases")
                                .HasColumnName("SaltwaterFish_CommonDiseases");

                            t.Property("Diet")
                                .HasColumnName("SaltwaterFish_Diet");

                            t.Property("FeedingFrequency")
                                .HasColumnName("SaltwaterFish_FeedingFrequency");

                            t.Property("FishType")
                                .HasColumnName("SaltwaterFish_FishType");

                            t.Property("FoodTypes")
                                .HasColumnName("SaltwaterFish_FoodTypes");

                            t.Property("IsJumper")
                                .HasColumnName("SaltwaterFish_IsJumper");

                            t.Property("IsSchooling")
                                .HasColumnName("SaltwaterFish_IsSchooling");

                            t.Property("MinTankSize")
                                .HasColumnName("SaltwaterFish_MinTankSize");

                            t.Property("OptimalSalinityMax")
                                .HasColumnName("SaltwaterFish_OptimalSalinityMax");

                            t.Property("OptimalSalinityMin")
                                .HasColumnName("SaltwaterFish_OptimalSalinityMin");

                            t.Property("OptimalTemperatureMax")
                                .HasColumnName("SaltwaterFish_OptimalTemperatureMax");

                            t.Property("OptimalTemperatureMin")
                                .HasColumnName("SaltwaterFish_OptimalTemperatureMin");

                            t.Property("ProneToIch")
                                .HasColumnName("SaltwaterFish_ProneToIch");

                            t.Property("RecommendedSchoolSize")
                                .HasColumnName("SaltwaterFish_RecommendedSchoolSize");

                            t.Property("RequiresHidingSpots")
                                .HasColumnName("SaltwaterFish_RequiresHidingSpots");

                            t.Property("RequiresQuarantine")
                                .HasColumnName("SaltwaterFish_RequiresQuarantine");

                            t.Property("SpecialRequirements")
                                .HasColumnName("SaltwaterFish_SpecialRequirements");

                            t.Property("SwimmingRegion")
                                .HasColumnName("SaltwaterFish_SwimmingRegion");

                            t.Property("TankMateCompatibility")
                                .HasColumnName("SaltwaterFish_TankMateCompatibility");

                            t.Property("Temperament")
                                .HasColumnName("SaltwaterFish_Temperament");

                            t.Property("pHRange")
                                .HasColumnName("SaltwaterFish_pHRange");
                        });

                    b.HasDiscriminator().HasValue("SaltwaterFish");
                });

            modelBuilder.Entity("AquaHub.Models.SaltwaterInvertebrate", b =>
                {
                    b.HasBaseType("AquaHub.Models.Livestock");

                    b.Property<double>("AdultSize")
                        .HasColumnType("double precision");

                    b.Property<bool>("AggressiveTowardsOwnSpecies")
                        .HasColumnType("boolean");

                    b.Property<int>("AverageLifespanYears")
                        .HasColumnType("integer");

                    b.Property<string>("Behavior")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CareLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Coloration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CommonDiseases")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Diet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FeedingFrequency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Habitat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("InvertebrateType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCleaner")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsReefSafe")
                        .HasColumnType("boolean");

                    b.Property<double>("MinTankSize")
                        .HasColumnType("double precision");

                    b.Property<double>("OptimalSalinityMax")
                        .HasColumnType("double precision");

                    b.Property<double>("OptimalSalinityMin")
                        .HasColumnType("double precision");

                    b.Property<double>("OptimalTemperatureMax")
                        .HasColumnType("double precision");

                    b.Property<double>("OptimalTemperatureMin")
                        .HasColumnType("double precision");

                    b.Property<string>("Placement")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RequiresAcclimation")
                        .HasColumnType("boolean");

                    b.Property<string>("SpecialRequirements")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TankMateCompatibility")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WaterParameters")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("pHRange")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("Livestock", t =>
                        {
                            t.Property("AdultSize")
                                .HasColumnName("SaltwaterInvertebrate_AdultSize");

                            t.Property("AggressiveTowardsOwnSpecies")
                                .HasColumnName("SaltwaterInvertebrate_AggressiveTowardsOwnSpecies");

                            t.Property("AverageLifespanYears")
                                .HasColumnName("SaltwaterInvertebrate_AverageLifespanYears");

                            t.Property("Behavior")
                                .HasColumnName("SaltwaterInvertebrate_Behavior");

                            t.Property("CareLevel")
                                .HasColumnName("SaltwaterInvertebrate_CareLevel");

                            t.Property("Coloration")
                                .HasColumnName("SaltwaterInvertebrate_Coloration");

                            t.Property("CommonDiseases")
                                .HasColumnName("SaltwaterInvertebrate_CommonDiseases");

                            t.Property("Diet")
                                .HasColumnName("SaltwaterInvertebrate_Diet");

                            t.Property("FeedingFrequency")
                                .HasColumnName("SaltwaterInvertebrate_FeedingFrequency");

                            t.Property("Habitat")
                                .HasColumnName("SaltwaterInvertebrate_Habitat");

                            t.Property("InvertebrateType")
                                .HasColumnName("SaltwaterInvertebrate_InvertebrateType");

                            t.Property("IsReefSafe")
                                .HasColumnName("SaltwaterInvertebrate_IsReefSafe");

                            t.Property("MinTankSize")
                                .HasColumnName("SaltwaterInvertebrate_MinTankSize");

                            t.Property("OptimalSalinityMax")
                                .HasColumnName("SaltwaterInvertebrate_OptimalSalinityMax");

                            t.Property("OptimalSalinityMin")
                                .HasColumnName("SaltwaterInvertebrate_OptimalSalinityMin");

                            t.Property("OptimalTemperatureMax")
                                .HasColumnName("SaltwaterInvertebrate_OptimalTemperatureMax");

                            t.Property("OptimalTemperatureMin")
                                .HasColumnName("SaltwaterInvertebrate_OptimalTemperatureMin");

                            t.Property("Placement")
                                .HasColumnName("SaltwaterInvertebrate_Placement");

                            t.Property("RequiresAcclimation")
                                .HasColumnName("SaltwaterInvertebrate_RequiresAcclimation");

                            t.Property("SpecialRequirements")
                                .HasColumnName("SaltwaterInvertebrate_SpecialRequirements");

                            t.Property("TankMateCompatibility")
                                .HasColumnName("SaltwaterInvertebrate_TankMateCompatibility");

                            t.Property("WaterParameters")
                                .HasColumnName("SaltwaterInvertebrate_WaterParameters");

                            t.Property("pHRange")
                                .HasColumnName("SaltwaterInvertebrate_pHRange");
                        });

                    b.HasDiscriminator().HasValue("SaltwaterInvertebrate");
                });

            modelBuilder.Entity("AquaHub.Models.DosingRecord", b =>
                {
                    b.HasOne("AquaHub.Models.Tank", "Tank")
                        .WithMany()
                        .HasForeignKey("TankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tank");
                });

            modelBuilder.Entity("AquaHub.Models.Equipment", b =>
                {
                    b.HasOne("AquaHub.Models.Tank", "Tank")
                        .WithMany("Equipment")
                        .HasForeignKey("TankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tank");
                });

            modelBuilder.Entity("AquaHub.Models.Livestock", b =>
                {
                    b.HasOne("AquaHub.Models.Tank", "Tank")
                        .WithMany("Livestock")
                        .HasForeignKey("TankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tank");
                });

            modelBuilder.Entity("AquaHub.Models.MaintenanceLog", b =>
                {
                    b.HasOne("AquaHub.Models.Tank", "Tank")
                        .WithMany("MaintenanceLogs")
                        .HasForeignKey("TankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tank");
                });

            modelBuilder.Entity("AquaHub.Models.Notification", b =>
                {
                    b.HasOne("AquaHub.Models.Reminder", "Reminder")
                        .WithMany()
                        .HasForeignKey("ReminderId");

                    b.HasOne("AquaHub.Models.Tank", "Tank")
                        .WithMany()
                        .HasForeignKey("TankId");

                    b.HasOne("AquaHub.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AquaHub.Models.WaterTest", "WaterTest")
                        .WithMany()
                        .HasForeignKey("WaterTestId");

                    b.Navigation("Reminder");

                    b.Navigation("Tank");

                    b.Navigation("User");

                    b.Navigation("WaterTest");
                });

            modelBuilder.Entity("AquaHub.Models.PhotoLog", b =>
                {
                    b.HasOne("AquaHub.Models.Tank", "Tank")
                        .WithMany()
                        .HasForeignKey("TankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tank");
                });

            modelBuilder.Entity("AquaHub.Models.Reminder", b =>
                {
                    b.HasOne("AquaHub.Models.Tank", "Tank")
                        .WithMany()
                        .HasForeignKey("TankId");

                    b.HasOne("AquaHub.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tank");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AquaHub.Models.Tank", b =>
                {
                    b.HasOne("AquaHub.Models.AppUser", "User")
                        .WithMany("Tanks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AquaHub.Models.UserNotificationSettings", b =>
                {
                    b.HasOne("AquaHub.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AquaHub.Models.WaterTest", b =>
                {
                    b.HasOne("AquaHub.Models.Tank", "Tank")
                        .WithMany("WaterTests")
                        .HasForeignKey("TankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tank");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AquaHub.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AquaHub.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserPasskey<string>", b =>
                {
                    b.HasOne("AquaHub.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Microsoft.AspNetCore.Identity.IdentityPasskeyData", "Data", b1 =>
                        {
                            b1.Property<byte[]>("IdentityUserPasskeyCredentialId");

                            b1.Property<byte[]>("AttestationObject")
                                .IsRequired();

                            b1.Property<byte[]>("ClientDataJson")
                                .IsRequired();

                            b1.Property<DateTimeOffset>("CreatedAt");

                            b1.Property<bool>("IsBackedUp");

                            b1.Property<bool>("IsBackupEligible");

                            b1.Property<bool>("IsUserVerified");

                            b1.Property<string>("Name");

                            b1.Property<byte[]>("PublicKey")
                                .IsRequired();

                            b1.Property<long>("SignCount");

                            b1.PrimitiveCollection<string>("Transports");

                            b1.HasKey("IdentityUserPasskeyCredentialId");

                            b1.ToTable("AspNetUserPasskeys");

                            b1.ToJson("Data");

                            b1.WithOwner()
                                .HasForeignKey("IdentityUserPasskeyCredentialId");
                        });

                    b.Navigation("Data")
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AquaHub.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AquaHub.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AquaHub.Models.AppUser", b =>
                {
                    b.Navigation("Tanks");
                });

            modelBuilder.Entity("AquaHub.Models.Tank", b =>
                {
                    b.Navigation("Equipment");

                    b.Navigation("Livestock");

                    b.Navigation("MaintenanceLogs");

                    b.Navigation("WaterTests");
                });
#pragma warning restore 612, 618
        }
    }
}
